replicaCount: 1

image:
  repository: ghcr.io/dwyer/devstream-portfolio
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

evn:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://db:5432/devstream
  - name: SPRING_DATASOURCE_USERNAME
    value: dev
  - name: SPRING_DATASOURCE_PASSWORD
    value: dev
  - name: SPRING_PROFILES_ACTIVE
    value: k8s